######################## default configuration ####################
baseURL = "https://www.segment-routing.ch/"
title = "Segment Routing"
languageCode = "en-us"
theme = "segment-routing-ch-theme"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "10"