######################## default configuration ####################
baseURL = "https://insrapperswil.github.io/segment-routing-ch.github.io/"
title = "Segment Routing"
languageCode = "en-us"
theme = "bigspring-hugo-startup-theme"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true
