######################## default configuration ####################
baseURL = "https://mbongard.github.io/segment-routing-ch.github.io/"
title = "Segment Routing"
languageCode = "en-us"
theme = "segment-routing-ch-theme"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "10"