############################# English ############################
[en]
languageName = "En"
title = "Segment Routing by INS"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "INS"
footer_menu_middle = "Contact"
footer_menu_right = "Discover"
footer_content = ""

# copyright
copyright = "Design By [Themefisher](https://themefisher.com/) - Developed By [Gethugothemes](https://gethugothemes.com/)"
