# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Articles"
url = "articles"
weight = 2

[[main]]
name = "Projects"
url = "projects"
weight = 3

[[main]]
name = "Courses"
url = "courses"
weight = 4

[[main]]
identifier = "about-us"
name = "About Us"
weight = 5

[[main.children]]
parent = "about-us"
name = "Team"
url = "about-us/team"

# footer menu left
[[footer_left]]
name = "INS Institute for Networked Solutions"
url = "about-us"
weight = 1

# footer menu left
[[footer_left]]
name = "8640 Rapperswil, Switzerland"
weight = 2

