# menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Articles"
url = "articles"
weight = 2

[[main]]
name = "Projects"
url = "projects"
weight = 3

[[main]]
name = "Courses"
url = "courses"
weight = 4

[[main]]
identifier = "ins"
name = "INS"
weight = 5

[[main]]
name = "About Us"
parent = "ins"
url = "ins/about-us"
weight = 1

[[main]]
name = "Contact Us"
parent = "ins"
url = "ins/contact-us"
weight = 2

# footer left
[[footer_left]]
name = "INS Institute for Networked Solutions"
url = "ins/about-us"
weight = 1
[footer_left.params]
    class = "mb-2"

# footer left
[[footer_left]]
name = "OST – Eastern Switzerland University of Applied Sciences"
url = "ins/contact-us"
weight = 2
[footer_left.params]
    class = "mb-2"

# footer left
[[footer_left]]
name = "Oberseestrasse 10"
weight = 3
[footer_left.params]
    class = "mb-0"

# footer left
[[footer_left]]
name = "8640 Rapperswil SG"
weight = 4
[footer_left.params]
    class = "mb-0"

# footer left
[[footer_left]]
name = "Switzerland"
weight = 5
[footer_left.params]
    class = "mb-0"

# footer middle
[[footer_middle]]
name = "Articles"
url = "articles"
weight = 1
[footer_middle.params]
    class = "mb-2"

# footer middle
[[footer_middle]]
name = "Projects"
url = "projects"
weight = 2
[footer_middle.params]
    class = "mb-2"

# footer middle
[[footer_middle]]
name = "Courses"
url = "courses"
weight = 3
[footer_middle.params]
    class = "mb-2"

# footer middle
[[footer_middle]]
name = "About Us"
url = "ins/about-us"
weight = 4
[footer_middle.params]
    class = "mb-2"

# footer middle
[[footer_middle]]
name = "Contact Us"
url = "ins/contact-us"
weight = 5
[footer_middle.params]
    class = "mb-2"
