# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Articles"
url = "articles"
weight = 2

[[main]]
name = "Projects"
url = "projects"
weight = 3

[[main]]
name = "Courses"
url = "courses"
weight = 4

[[main]]
name = "About Us"
url = "about-us"
weight = 5

# footer menu left
[[footer_left]]
name = "tbd"
url = "#"

[[footer_left]]
name = "tbd"
url = "#"

[[footer_left]]
name = "tbd"
url = "#"


# footer menu middle
[[footer_middle]]
name = "tbd"
url = "#"

[[footer_middle]]
name = "tbd"
url = "#"

[[footer_middle]]
name = "tbd"
url = "#"

# footer menu right
[[footer_right]]
name = "tbd"
url = "#"

[[footer_right]]
name = "tbd"
url = "#"

[[footer_right]]
name = "tbd"
url = "#"
