# menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Articles"
url = "articles"
weight = 2

[[main]]
name = "Projects"
url = "projects"
weight = 3

[[main]]
name = "Courses"
url = "courses"
weight = 4

[[main]]
identifier = "about-us-main-menu"
name = "About Us"
weight = 5

# footer languages.en.menu left
[[footer_left]]
name = "INS Institute for Networked Solutions"
url = "about-us"
weight = 1

# footer languages.en.menu left
[[footer_left]]
name = "8640 Rapperswil, Switzerland"
weight = 2

