#################### default parameters ################################
logo = "images/logo.png"
logo_width = "300px"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "INSRapperswil"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# navigation buttons
[navigation_button]
enable = false
label = "Get Started"
link = "contact"
  
# social sites

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/Segment_Routing"
