#################### default parameters ################################
logo = "images/logo.png"
logo_width = "300px"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "INSRapperswil"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# navigation buttons
[navigation_button]
enable = false
label = "Get Started"
link = "contact"
  
# social sites

[[social]]
title = "Twitter"
icon = "fab fa-twitter" 
link = "https://twitter.com/Segment_Routing"

[[social]]
title = "Phone"
icon = "fas fa-phone"
link = "tel:+41552221838"

[[social]]
title = "E-Mail"
icon = "fas fa-envelope"
link = "mailto:cloud-networking@ost.ch"

[[social]]
title = "WhatsApp"
icon = "fab fa-whatsapp"
link = "https://wa.me/+41552221838"